apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 3  # The number of instances of your app you want to run
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodejs-container
        image: ghcr.io/andreicozari/welcome-to-docker:latest  # Replace with your image
        ports:
        - containerPort: 3000  # The port your app listens on
        resources:
          requests:
            memory: "128Mi"  # Minimum amount of memory guaranteed to the container
            cpu: "250m"     # Fraction of a CPU guaranteed to the container (250 millicpus = 0.25 CPUs)
          limits:
            memory: "512Mi" # Maximum amount of memory the container can use
            cpu: "500m"     # Maximum CPU the container can use
