name: Docker Build and Push

on:
  workflow_run:
    workflows: ["npm-build"]  # Name of the first workflow
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: andreicozari
          password: ${{ secrets.GHRC_IO_ACCESS_TOKEN_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ../
          push: true
          tags: ghcr.io/andreicozari/welcome-to-docker:latest
