name: Docker Build and Push

on:
  push:
    branches: [ main ]
    # You can specify more conditions like tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.andreicozari }}
          password: ${{ secrets.GHRC_IO_ACCESS_TOKEN_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/andreicozari/welcome-to-docker:latest
